[project.extra]
homepage = "https://www.apocfly.com"

[project.theme]  # 项目主题
variant = "modern"
#font.code = "JetBrains Mono"
#font.text = "Noto Sans Simplified Chinese"
#fonts = "JetBrains Mono"
language = "zh"
direction = "ltr"  # left to right 自作向右 阅读
favicon = "images/Logo.svg"
logo = "images/Logo.svg"

features = [
    # 代码框
    "content.action.edit",
    "content.action.view",
    "content.action.edit",
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",

    # 导航栏
    "navigation.path",
#    "navigation.instant",
#    "navigation.instant.prefetch",
#    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.sections",
    "navigation.expand",
#    "navigation.prune",  # 仅可见的导航项会被包含在渲染的 HTML 中
    "navigation.top",  # 返回顶部按钮
    "navigation.tabs",  # 将导航栏放置于顶部
    "navigation.footer",
#    "navigation.indexes",

#    "toc.integrate",

    # 搜索
    "search.highlight",
    "search.suggest",
    "search.highlight",
    "search.share",

]


[project]
docs_dir = "docs"

site_name = "APOCFLY模拟飞行·文档站"
site_description = "Use Markdown language to finish the Operating document."
site_url = "https://docs.apocfly.com"

repo_url = "https://github.com/apocfly/Operating-document"
repo_name = "apocfly/Operating-document"
edit_uri = "edit/main/docs/"

# CC BY-SA 4.0
site_author = "Yiheng Master Gui"
copyright = """本项目的全部文字在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0(知识共享 署名-相同方式共享 4.0协议)</a> 之条款下提供，附加条款亦可能应用。<a href="https://github.com/supermastergui" target="_blank" rel="noopener noreferrer">Yiheng Master Gui</a> 保留所有未明示授予的权利。 <br> Intended for simulator only, Do not use for reality | 仅供模拟飞行使用，请勿用于真实飞行"""

# extra_javascript = ["javascripts/feedback.js"]  # 反馈js

# use_directory_urls = false # 在任意文档的URL后加入.html, 避免错误

extra_css = ["stylesheets/extra.css"] # 引入外部css

# 设置目录
nav = [
    { "主页" = "index.md" },
    { "教程目录" = "Contents.md" },
    { "总则" = [
        "General/index.md",
        {"行为准则" = "General/OPDOC-General-202502-R2-SC.md"},
        {"标准文件发行格式" = "General/OPDOC-General-202501-R3-SC.md"},
        {"工作报告" = [
            {"空管中心·第三季度工作报告" = "General/Work_report/OPDOC-CTD-WR-202503-R0.md"},
            {"2025第四季度工作报告暨2026新年贺词" = "General/Work_report/OPDOC-General-WR-202601-R0.md"},
        ] },
        {"会议记录" = [
            {"2025年第一次全体职员会议" = "General/Meeting/OPDOC-MT-202501-R0-SC.md"},
            {"2025年管制员训练部会议" = "General/Meeting/OPDOC-MT-202502-R0-SC.md"},
        ] }
    ]},
    { "管制员训练部" = [
        "CTD/index.md",
        {"管制员培训大纲" = "CTD/OPDOC-CTD-202501-R4-SC.md"},
        {"管制员训练部·学习中心" = [
            "CTD/Learning_Center/index.md",
#            {"陆空对话（空中交通无线电通话用语）" = "../../PTD/Learning_Center/Radiotelephony_Communications_for_Air_Traffic_Services/"},
#            {"Metar报文解读" = "../../PTD/Learning_Center/References/%E5%9B%BD%E9%99%85%E6%B0%94%E8%B1%A1%E6%8A%A5%E6%96%87%E8%A7%A3%E7%A0%81.pdf"},
#            {"eAIP航图解读" = "../../PTD/Learning_Center/References/%E8%88%AA%E5%9B%BE%E8%AF%86%E8%AF%BB.pdf"},
#            {"RVSM飞行高度层" = "../../PTD/Learning_Center/RVSM_flight_level/"},
#            {"飞行情报区" = "../../PTD/Learning_Center/FIR/"},
#            {"空域" = "../../PTD/Learning_Center/Airspace/"},
#            {"班机航路的查询教程" = "../../PTD/Learning_Center/Airlines_flight_route/"},
#            {"应答机分配" = "CTD/Learning_Center/Squawk.md"},
#            {"PBN进离场" = "http://www.caac.gov.cn/XXGK/XXGK/ZCJD/202505/P020250515551921206047.pdf"},
#            {"先导宣传片" = "CTD/Learning_Center/teaser_trailer.md"}
        ]},
    ]},
    { "飞行员训练部" = [
#        "PTD/index.md",
        {"飞行员训练部·学习中心" = [
#            "PTD/Learning_Center/index.md",
            {"Swift 连飞教程" = "PTD/Learning_Center/Swift_Connected_Flight_Tutorial.md"},
            {"Cpilot 连飞教程" = "PTD/Learning_Center/Cpilot_Tutorial.md"},
            {"TeamSpeak 3 使用教程" = "PTD/Learning_Center/TeamSpeak_Tutorial.md"},
            {"陆空对话（空中交通无线电通话用语）" = "PTD/Learning_Center/Radiotelephony_Communications_for_Air_Traffic_Services.md"},
            {"Metar报文解读" = "PTD/Learning_Center/References/%E5%9B%BD%E9%99%85%E6%B0%94%E8%B1%A1%E6%8A%A5%E6%96%87%E8%A7%A3%E7%A0%81.pdf"},
            {"eAIP航图解读" = "PTD/Learning_Center/References/%E8%88%AA%E5%9B%BE%E8%AF%86%E8%AF%BB.pdf"},
            {"气压基准与TL、TA、TH及高度表拨正" = "PTD/Learning_Center/TL_TA_TH.md"},
            {"RVSM飞行高度层" = "PTD/Learning_Center/RVSM_flight_level.md"},
            {"飞行情报区" = "PTD/Learning_Center/FIR.md"},
            {"空域" = "PTD/Learning_Center/Airspace.md"},
            {"PBN进离场" = "http://www.caac.gov.cn/XXGK/XXGK/ZCJD/202505/P020250515551921206047.pdf"},
            {"班机航路的查询教程" = "PTD/Learning_Center/Airlines_flight_route.md"}
        ]}
    ]},
    {"标准运行程序·SOP" = [
        {"管制员训练部" = [
            "CTD/SOP/index.md",
            {"EuroScope 标准操作流程" = "CTD/SOP/EuroScope.md" },
            {"管制面试 Interview 标准操作流程" = "CTD/SOP/Interview.md"},
            {"在线管理员 Supervisor 标准操作流程" = "CTD/SOP/Supervisor.md"},
        ]},
    ]},
    { "技术" = [
        "Programming/index.md",
        {"Simple FSD" = "Programming/FSD/index.md"},
        {"China-Mainland-Sector" = "Programming/Sectors/index.md"},
        {"Operating-document" = [
#            "",
            {"贡献者公约" = "CODE_OF_CONDUCT.md"},
            {"CC BY-SA 4.0 License" = "LICENSE.md"},
            {"贡献指南" = "Contribution_guidelines.md"},
            {"Github主页" = "https://github.com/apocfly/Operating-document"}
        ]}
    ]},

]

# [project.extra.analytics]
# provider: custom
# property: foobar


[project.extra.consent]
title = "Cookie 许可"
description = """
    我们使用Cookie来识别您的重复访问和偏好，并衡量我们文档的有效性以及用户是否能找到他们正在搜索的内容。在您同意的情况下，您正在帮助我们改进我们的文档。
"""

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/apocfly/Operating-document"

#[[project.extra.social]]
#icon = "fontawesome/brands/bilibili"
#link = "https://space.bilibili.com/XXXXXXXXXXXX"
#
#[[project.extra.social]]
#icon = "fontawesome/brands/tiktok"
#link = "https://v.douyin.com/XXXXXXXXXXX"

[[project.extra.social]]
icon = "fontawesome/brands/qq"
link = "https://qm.qq.com/q/6afOpkDMB2"

# [project.extra.analytics]
# provider : custom
# property : foobar

# Markwodn 扩展
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "underscore"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
key_map= {"lbutton_cn" = "鼠标左键", "rbutton_cn" = "鼠标右键"}
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

#[project.markdown_extensions.abbr]
#[project.markdown_extensions.admonition]
#[project.markdown_extensions.attr_list]
#[project.markdown_extensions.def_list]
#[project.markdown_extensions.footnotes]
#[project.markdown_extensions.md_in_html]
#[project.markdown_extensions.toc]
#[project.markdown_extensions.pymdownx.arithmatex]
#[project.markdown_extensions.pymdownx.betterem]
#[project.markdown_extensions.pymdownx.caret]
#[project.markdown_extensions.pymdownx.details]
#[project.markdown_extensions.pymdownx.emoji]
#[project.markdown_extensions.pymdownx.highlight]
#[project.markdown_extensions.pymdownx.inlinehilite]
#[project.markdown_extensions.pymdownx.keys]
#[project.markdown_extensions.pymdownx.mark]
#[project.markdown_extensions.pymdownx.smartsymbols]
#[project.markdown_extensions.pymdownx.superfences]
#[project.markdown_extensions.pymdownx.tabbed]
#[project.markdown_extensions.pymdownx.tasklist]
#[project.markdown_extensions.pymdownx.tilde]